alias: Kitchen Motion - Lights - TimeOfDay
description: >-
  Using a counter and time of day - decide which lights to turn on and for how
  long
trigger:
  - platform: state
    entity_id: binary_sensor.kitchenmotion_occupancy
    from: 'off'
    to: 'on'
action:
  - choose:
      - conditions:
          - condition: sun
            after: sunrise
            after_offset: '-1:30:00'
          - condition: time
            before: '09:00:00'
          - condition: numeric_state
            entity_id: counter.kitchen_motion_counter
            below: '1'
        sequence:
          - scene: scene.kitchen_all_no_cans
          - service: counter.increment
            target:
              entity_id: counter.kitchen_motion_counter
          - delay:
              hours: 0
              minutes: 0
              seconds: 15
              milliseconds: 0
          - service: scene.turn_on
            target:
              entity_id: scene.kitchen_all_on
      - conditions:
          - condition: sun
            after: sunrise
            after_offset: '-1:30:00'
          - condition: time
            before: '08:00:00'
          - condition: numeric_state
            entity_id: counter.kitchen_motion_counter
            above: '0'
        sequence:
          - scene: scene.kitchen_all_on
          - service: counter.increment
            target:
              entity_id: counter.kitchen_motion_counter
      - conditions:
          - condition: sun
            after: sunset
          - condition: time
            before: '21:00:00'
          - condition: numeric_state
            entity_id: counter.kitchen_motion_counter
            above: '0'
        sequence:
          - scene: scene.kitchen_all_on
          - service: counter.increment
            target:
              entity_id: counter.kitchen_motion_counter
      - conditions:
          - condition: time
            after: '21:00:00'
          - condition: time
            before: '23:59:59'
        sequence:
          - scene: scene.kitchen_all_no_cans
          - service: counter.increment
            target:
              entity_id: counter.kitchen_motion_counter
      - conditions:
          - condition: time
            after: '00:00:00'
          - condition: sun
            before: sunrise
            before_offset: '-1:30:00'
        sequence:
          - scene: scene.kitchen_late_night
          - service: counter.increment
            target:
              entity_id: counter.kitchen_motion_counter
    default:
      - scene: scene.kitchen_cans_cabinets
      - service: counter.increment
        target:
          entity_id: counter.kitchen_motion_counter
  - wait_for_trigger:
      platform: state
      entity_id: binary_sensor.kitchenmotion_occupancy
      from: 'on'
      to: 'off'
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - choose:
      - conditions:
          - condition: sun
            after: sunrise
            after_offset: '-1:30:00'
          - condition: time
            before: '09:00:00'
        sequence:
          - delay:
              hours: 0
              minutes: 5
              seconds: 0
              milliseconds: 0
          - scene: scene.kitchen_all_no_cans
          - delay:
              hours: 0
              minutes: 10
              seconds: 0
              milliseconds: 0
          - scene: scene.kitchen_all_off
          - service: counter.increment
            target:
              entity_id: counter.kitchen_motion_counter
      - conditions:
          - condition: sun
            after: sunset
          - condition: time
            before: '21:00:00'
          - condition: numeric_state
            entity_id: counter.kitchen_motion_counter
            above: '0'
        sequence:
          - delay:
              hours: 0
              minutes: 5
              seconds: 0
              milliseconds: 0
          - scene: scene.kitchen_all_no_cans
          - delay:
              hours: 0
              minutes: 10
              seconds: 0
              milliseconds: 0
          - scene: scene.kitchen_dim
          - delay:
              hours: 1
              minutes: 0
              seconds: 0
              milliseconds: 0
          - scene: scene.kitchen_all_off
          - service: counter.increment
            target:
              entity_id: counter.kitchen_motion_counter
      - conditions:
          - condition: time
            after: '21:00:00'
          - condition: time
            before: '23:59:59'
          - condition: numeric_state
            entity_id: counter.kitchen_motion_counter
            above: '0'
        sequence:
          - delay:
              hours: 0
              minutes: 5
              seconds: 0
              milliseconds: 0
          - scene: scene.kitchen_dim
          - delay:
              hours: 1
              minutes: 0
              seconds: 0
              milliseconds: 0
          - scene: scene.kitchen_all_off
          - service: counter.increment
            target:
              entity_id: counter.kitchen_motion_counter
    default:
      - scene: scene.kitchen_all_off
mode: restart
max_exceeded: silent
